"""initial PostgreSQL schema

Revision ID: 13ecd0272470
Revises:
Create Date: 2026-09-11 11:07:33.959230
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '13ecd0272470'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('senha', sa.Text(), nullable=False),
    sa.Column('tipo_perfil', sa.String(length=80), server_default='Apenas Financeiro', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('cartoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('limite_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('dia_fechamento', sa.Integer(), nullable=False),
    sa.Column('dia_vencimento', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('dia_fechamento BETWEEN 1 AND 31', name='ck_cartoes_fechamento'),
    sa.CheckConstraint('dia_vencimento BETWEEN 1 AND 31', name='ck_cartoes_vencimento'),
    sa.CheckConstraint('limite_total > 0', name='ck_cartoes_limite_positivo'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'usuario_id', name='uq_cartoes_nome_usuario')
    )
    op.create_index('ix_cartoes_usuario', 'cartoes', ['usuario_id'], unique=False)
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('tipo', sa.String(length=30), server_default='digital', nullable=False),
    sa.Column('saldo_inicial', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('principal', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'usuario_id', name='uq_contas_nome_usuario')
    )
    op.create_index('ix_contas_usuario', 'contas', ['usuario_id'], unique=False)
    op.create_index(
        'uq_contas_principal_usuario',
        'contas',
        ['usuario_id'],
        unique=True,
        postgresql_where=sa.text('principal IS TRUE AND ativo IS TRUE'),
        sqlite_where=sa.text('principal IS 1 AND ativo IS 1'),
    )
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=160), nullable=False),
    sa.Column('tipo', sa.String(length=80), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('valor_total > 0', name='ck_vendas_valor_positivo'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vendas_usuario_data', 'vendas', ['usuario_id', 'data'], unique=False)
    op.create_table('faturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cartao_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('ano_referencia', sa.Integer(), nullable=False),
    sa.Column('mes_referencia', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fechamento', sa.Date(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('mes_referencia BETWEEN 1 AND 12', name='ck_faturas_mes'),
    sa.ForeignKeyConstraint(['cartao_id'], ['cartoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cartao_id', 'ano_referencia', 'mes_referencia', name='uq_faturas_cartao_periodo')
    )
    op.create_index('ix_faturas_cartao_periodo', 'faturas', ['cartao_id', 'ano_referencia', 'mes_referencia'], unique=False)
    op.create_table('limites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('mes', sa.String(length=7), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('valor > 0', name='ck_limites_valor_positivo'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria_id', 'mes', 'usuario_id', name='uq_limites_categoria_mes_usuario')
    )
    op.create_index('ix_limites_usuario_mes', 'limites', ['usuario_id', 'mes'], unique=False)
    op.create_table('parcelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pendente', nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('valor > 0', name='ck_parcelas_valor_positivo'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parcelas_usuario_status', 'parcelas', ['usuario_id', 'status'], unique=False)
    op.create_index('ix_parcelas_venda', 'parcelas', ['venda_id'], unique=False)
    op.create_table('transacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('conta_id', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("tipo IN ('entrada', 'saida')", name='ck_transacoes_tipo'),
    sa.CheckConstraint('valor > 0', name='ck_transacoes_valor_positivo'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transacoes_categoria', 'transacoes', ['categoria_id'], unique=False)
    op.create_index('ix_transacoes_conta', 'transacoes', ['conta_id'], unique=False)
    op.create_index('ix_transacoes_usuario_data', 'transacoes', ['usuario_id', 'data'], unique=False)
    op.create_table('transferencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_origem_id', sa.Integer(), nullable=False),
    sa.Column('conta_destino_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('conta_origem_id <> conta_destino_id', name='ck_transferencias_contas_distintas'),
    sa.CheckConstraint('valor > 0', name='ck_transferencias_valor_positivo'),
    sa.ForeignKeyConstraint(['conta_destino_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['conta_origem_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transferencias_usuario_data', 'transferencias', ['usuario_id', 'data'], unique=False)
    op.create_table('compras_cartao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cartao_id', sa.Integer(), nullable=False),
    sa.Column('fatura_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizada_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('valor > 0', name='ck_compras_cartao_valor_positivo'),
    sa.ForeignKeyConstraint(['cartao_id'], ['cartoes.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['fatura_id'], ['faturas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compras_cartao_fatura', 'compras_cartao', ['fatura_id'], unique=False)
    op.create_index('ix_compras_cartao_usuario_data', 'compras_cartao', ['usuario_id', 'data'], unique=False)
    op.create_table('pagamentos_fatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fatura_id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('valor > 0', name='ck_pagamentos_fatura_valor_positivo'),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['fatura_id'], ['faturas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fatura_id')
    )
    op.create_index('ix_pagamentos_fatura_conta', 'pagamentos_fatura', ['conta_id'], unique=False)
    op.create_index('ix_pagamentos_fatura_usuario', 'pagamentos_fatura', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pagamentos_fatura_usuario', table_name='pagamentos_fatura')
    op.drop_index('ix_pagamentos_fatura_conta', table_name='pagamentos_fatura')
    op.drop_table('pagamentos_fatura')
    op.drop_index('ix_compras_cartao_usuario_data', table_name='compras_cartao')
    op.drop_index('ix_compras_cartao_fatura', table_name='compras_cartao')
    op.drop_table('compras_cartao')
    op.drop_index('ix_transferencias_usuario_data', table_name='transferencias')
    op.drop_table('transferencias')
    op.drop_index('ix_transacoes_usuario_data', table_name='transacoes')
    op.drop_index('ix_transacoes_conta', table_name='transacoes')
    op.drop_index('ix_transacoes_categoria', table_name='transacoes')
    op.drop_table('transacoes')
    op.drop_index('ix_parcelas_venda', table_name='parcelas')
    op.drop_index('ix_parcelas_usuario_status', table_name='parcelas')
    op.drop_table('parcelas')
    op.drop_index('ix_limites_usuario_mes', table_name='limites')
    op.drop_table('limites')
    op.drop_index('ix_faturas_cartao_periodo', table_name='faturas')
    op.drop_table('faturas')
    op.drop_index('ix_vendas_usuario_data', table_name='vendas')
    op.drop_table('vendas')
    op.drop_index('uq_contas_principal_usuario', table_name='contas')
    op.drop_index('ix_contas_usuario', table_name='contas')
    op.drop_table('contas')
    op.drop_table('categorias')
    op.drop_index('ix_cartoes_usuario', table_name='cartoes')
    op.drop_table('cartoes')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
